# Generated by Django 5.1.5 on 2026-09-01 16:41
#
# BORDER SENTINEL - AI-Based Fake Identity & Document Screening System
# ---------------------------------------------------------------------
# Initial schema for the screening platform.  Four tables:
#
#   ScreeningRecord  - one row per analysed document: the uploaded images,
#                      the extracted identity fields, every validation rule
#                      result, the tampering-detector readings, the face
#                      verification outcome and the composite risk score are
#                      persisted as JSON blobs so a case can be re-opened and
#                      reviewed exactly as the engine saw it.
#   AuditEvent       - append-only, hash-chained digital trail
#                      (seq + prev_hash + sha256) giving every record a
#                      tamper-evident history for investigations.
#   WatchlistEntry   - person watchlist consulted by Module 2 (fuzzy name
#                      and document-number matching).
#   ExpiredDocument  - lost / stolen / expired travel-document blacklist
#                      consulted by Module 2.
#
# The migration is idempotent on fresh databases (`migrate` applies it once)
# and was generated from screening/models.py; regenerate with
# `python manage.py makemigrations screening` after model changes.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """Creates the initial BORDER SENTINEL schema (see module comment)."""

    initial = True

    dependencies = [
    ]

    operations = [
        # Blacklist of reported lost / stolen / expired document numbers.
        migrations.CreateModel(
            name='ExpiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=30, unique=True)),
                ('doc_type', models.CharField(default='passport', max_length=30)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        # Core case table: inputs, per-module outputs and the risk verdict.
        migrations.CreateModel(
            name='ScreeningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa'), ('id_card', 'National ID'), ('driving_license', 'Driving Licence'), ('permit', 'Permit')], max_length=30)),
                ('original', models.FileField(upload_to='documents/')),
                ('live_photo', models.FileField(blank=True, null=True, upload_to='live/')),
                ('holder_name', models.CharField(blank=True, default='', max_length=160)),
                ('doc_number', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', max_length=8)),
                ('recommendation', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('CLEARED', 'Cleared'), ('FLAGGED', 'Flagged')], default='NEW', max_length=10)),
                ('review_note', models.TextField(blank=True, default='')),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('processing_ms', models.IntegerField(default=0)),
                ('fields_json', models.JSONField(blank=True, default=dict)),
                ('checks_json', models.JSONField(blank=True, default=list)),
                ('tamper_json', models.JSONField(blank=True, default=dict)),
                ('face_json', models.JSONField(blank=True, default=dict)),
                ('scoring_json', models.JSONField(blank=True, default=dict)),
                ('annotated', models.CharField(blank=True, default='', max_length=255)),
                ('integrity_hash', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # Person-of-interest list used by the validation rules.
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('doc_number', models.CharField(blank=True, max_length=30)),
                ('nationality', models.CharField(blank=True, max_length=3)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # Hash-chained audit trail (digital trail requirement).
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('action', models.CharField(max_length=60)),
                ('detail', models.TextField(blank=True, default='')),
                ('prev_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='screening.screeningrecord')),
            ],
            options={
                'ordering': ['record', 'seq'],
            },
        ),
    ]
