# Generated by Django 5.2.17 on 2026-09-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistentry',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('visa', 'Visa'), ('id_card', 'National ID / Aadhaar'), ('driving_license', 'Driving Licence'), ('permit', 'Permit'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='watchlist/'),
        ),
    ]
