# Generated by Django 5.2.17 on 2026-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_watchlistentry_doc_type_watchlistentry_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expireddocument',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='blacklist/'),
        ),
        migrations.AlterField(
            model_name='expireddocument',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa'), ('id_card', 'National ID / Aadhaar'), ('driving_license', 'Driving Licence'), ('permit', 'Permit'), ('other', 'Other')], default='passport', max_length=30),
        ),
    ]
